---
title: "non-exposed US control samples - GCRC"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

## data cleaning

negative controls are non-malaria infected individuals from the USA controls (GCRC, General Clinical Research Center)

```{r}
rute <- "data-raw/Microarray results - First analysis wDNAfree controls.xlsx"
data_uscntrl <- read_xlsx(path = rute) %>% 
  janitor::clean_names() %>% 
  select(x1:x6,unexposed_controls:x56) %>% 
  filter(!is.na(x56)) %>% 
  filter(!is.na(x1)) %>% 
  rename(x50=unexposed_controls) %>% 
  mutate(across(.cols = x50:x56,.fns = as.numeric)) %>% 
  # tail(n=100)
  mutate(x6=snakecase::to_snake_case(x6)) %>%
  filter(str_starts(string = x6,
                    pattern = "PF|pf|PV|pv|NODNA|nodna")) %>%
  select(-(x1:x5)) %>% 
  mutate(x6=janitor::make_clean_names(x6))
  #epihelper::print_inf()
```

```{r}
anti <- data_uscntrl %>% 
  filter(str_starts(string = x6,
                    pattern = "PF|pf|PV|pv")) %>% 
  column_to_rownames(var = "x6")
```

```{r}
ctrl <- data_uscntrl %>% 
  filter(str_starts(string = x6,pattern = "nodna")) %>% 
  summarise_if(is.numeric,funs(median)) %>% 
  # MEDIAN to NORMALIZE against noDNA controls
  mutate(x6="nodna") %>% 
  column_to_rownames(var = "x6")
```


```{r}
ctrm <- NULL # crear objeto vacío
# loop para generar una matriz de las dimensiones de `anti`
for(i in 1:nrow(anti)){
  ctrm <- rbind(ctrm,ctrl)
}
# dimensiones de la matriz con la mediana de ctrls `noDNA` creada
dim(ctrm)
dim(anti)
# matriz con la mediana de ctrls `noDNA` para las 8 primeras muestras
# ctrm[1:8,] #%>% class()
```


```{r}
# definir resultado para los valores menores o iguales a cero:
# log2.NA = function(x) {log2(ifelse(x>0, x, NA))}

# normalización con respecto a los controles `noDNA` 
# c/ transformación log2
norm <- log2(anti/ctrm) %>% 
  rownames_to_column(var = "x6") %>% 
  as_tibble() %>% 
  mutate(across(.cols = x50:x56,
                .fns = ~if_else(condition = .x==-Inf,
                               true = NA_real_,
                               false = .x))) %>% 
  mutate(x6specie=case_when(
    str_starts(x6,"pf") ~ "pf",
    str_starts(x6,"pv") ~ "pv",
    TRUE ~ NA_character_
  )) #%>% 
  #count(x6specie)
```

```{r}
norm %>% 
  pivot_longer(cols = x50:x56,
               names_to = "usctrl",
               values_to = "usvalue") %>% 
  ggplot(aes(x = usvalue)) +
  geom_histogram()
```

```{r}
norm %>% 
  pivot_longer(cols = x50:x56,
               names_to = "usctrl",
               values_to = "usvalue") %>% 
  ggplot(aes(x = usvalue)) +
  geom_histogram() +
  facet_grid(~x6specie)
```

```{r,eval=FALSE}
norm %>% 
  filter(x6specie=="pv") %>% 
  pivot_longer(cols = x50:x56,
               names_to = "usctrl",
               values_to = "usvalue") %>% 
  ggplot(aes(x = usvalue,y = x6)) +
  geom_point()
```

## output

```{r}
usctrlpv <- norm %>% 
  filter(x6specie=="pv") %>% 
  filter(!str_detect(x6,"pvivax")) %>% 
  mutate(x6 = str_to_upper(x6)) %>% 
  mutate(x6=str_replace_all(x6,"_O_","o")) %>% 
  mutate(x6=str_replace_all(x6,"_S_","_S")) %>% 
  select(-x6specie) %>% 
  mutate(x6=case_when(
    str_detect(x6,"PVX_100680") ~ "PVX_100680_1o1",
    str_detect(x6,"PVX_003825_RENAMED") ~ "PVX_003825",
    str_detect(x6,"PVX_083240_RENAMED") ~ "PVX_083240",
    str_detect(x6,"PVX_085915_RENAMED") ~ "PVX_085915 (renamed)",
    str_detect(x6,"PVX_095185_RENAMED") ~ "PVX_095185",
    str_detect(x6,"PVX_097720_RENAMED") ~ "PVX_097720",
    str_detect(x6,"PVX_082700_RENAMED_0") ~ "PVX_082700 (renamed0",
    TRUE ~ x6
  ))
```

```{r}
eset.VIVAX.SEV.FILTER <- 
  readr::read_rds("data/04-eset_vivax_sev_filter.rds")

preanalysis <- eset.VIVAX.SEV.FILTER@assayData$exprs %>% 
  as_tibble(rownames = "feature") %>% 
  mutate(num = str_replace(feature,"(.+)\\.(.+)","\\2"),
         orf = str_replace(feature,"(.+)\\.(.+)","\\1")) %>% 
  select(feature,orf,num,everything())

expression_set <- preanalysis %>% 
  left_join(usctrlpv,by = c("orf" = "x6")) %>% 
  select(-orf,-num)
  # glimpse()
  # naniar::vis_miss()
  # filter(is.na(x50)) %>% 
  # select(feature:num) %>% 
  # arrange(orf)
```

```{r}
# usctrlpv %>% 
#   filter(str_detect(x6,"PVX_082700")) %>% 
#   arrange(x6) %>% 
#   mutate(x6=case_when(
#     # str_detect(x6,"PVX_100680") ~ "PVX_100680_1o1",
#     # str_detect(x6,"PVX_003825_RENAMED") ~ "PVX_003825",
#     # str_detect(x6,"PVX_083240_RENAMED") ~ "PVX_083240",
#     # str_detect(x6,"PVX_085915_RENAMED") ~ "PVX_085915 (renamed)",
#     # str_detect(x6,"PVX_095185_RENAMED") ~ "PVX_095185",
#     # str_detect(x6,"PVX_097720_RENAMED") ~ "PVX_097720",
#     # str_detect(x6,"PVX_082700_RENAMED_0") ~ "PVX_082700 (renamed0",
#     TRUE ~ x6
#   ))
# 
# preanalysis %>% 
#   filter(str_detect(orf,"PVX_082700")) %>% 
#   select(feature:num) %>% 
#   arrange(orf)
```

```{r}
expression_set_long <- expression_set %>% 
  pivot_longer(cols = -feature,
               names_to = "samples",
               values_to = "values") %>% 
  mutate(type=case_when(
    str_starts(samples,"LIM") ~ "sample",
    str_starts(samples,"x") ~ "control",
    TRUE ~ NA_character_
  ))

expression_pheno <- expression_set %>% 
  select(-feature) %>% 
  colnames() %>% 
  enframe(name = NULL,value = "samples") %>% 
  mutate(type=case_when(
    str_starts(samples,"LIM") ~ "sample",
    str_starts(samples,"x") ~ "control",
    TRUE ~ NA_character_
  )) %>% 
  epihelper::print_inf()
```

```{r}
expression_set_long %>% 
  ggplot(aes(x = values, fill = type)) +
  geom_histogram(position = position_identity(),alpha = 0.5)
```

```{r}
expression_set_long %>% 
  ggplot(aes(x = values, y = feature, color = type)) +
  geom_point(alpha = 0.5)
```

### build experessionSet

```{r}
expression_set
expression_pheno
```

pendientes:
   - unir elementos en un expressionSet
   - calcular features con intensidad diferencial entre muestras y controles
   - contabilizar cantidades en cada paso: original -> filtrado -> us-control

```{r}

```

